### ISSUE TITLE
Column not found: 1054 Unknown column '0.slug'

### ISSUE THREAD

**Issue by Rapp-colince** [Beaten-Sect0r/yii2-core#14]
Странный запрос генерится в MySQL.
```
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '0.slug' in 'where clause'' in E:\root\yiicore.dg\vendor\yiisoft\yii2\db\Command.php:915
Stack trace:
#0 E:\root\yiicore.dg\vendor\yiisoft\yii2\db\Command.php(915): PDOStatement->execute()
#1 E:\root\yiicore.dg\vendor\yiisoft\yii2\db\Command.php(388): yii\db\Command->queryInternal('queryScalar()
#3 E:\root\yiicore.dg\vendor\yiisoft\yii2\validators\UniqueValidator.php(171): yii\db\Query->exists()
#4 E:\root\yiicore.dg\vendor\yiisoft\yii2\validators\UniqueValidator.php(135): yii\validators\UniqueValidator->modelExists('validateAttribute(Object(backend\models\search\TagSearch), 'makeUnique('trigger('runWithParams('[]')
#18 E:\root\yiicore.dg\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('handleRequest(Object(yii\web\Request))
#21 E:\root\yiicore.dg\backend\web\index.php(32): yii\base\Application->run()
#22 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '0.slug' in 'where clause'
The SQL being executed was: SELECT EXISTS(SELECT * FROM `tag` WHERE (`0`.`slug`=''))' in E:\root\yiicore.dg\vendor\yiisoft\yii2\db\Schema.php:636
Stack trace:
#0 E:\root\yiicore.dg\vendor\yiisoft\yii2\db\Command.php(930): yii\db\Schema->convertException(Object(PDOException), 'SELECT EXISTS(S...')
#1 E:\root\yiicore.dg\vendor\yiisoft\yii2\db\Command.php(388): yii\db\Command->queryInternal('queryScalar()
#3 E:\root\yiicore.dg\vendor\yiisoft\yii2\validators\UniqueValidator.php(171): yii\db\Query->exists()
#4 E:\root\yiicore.dg\vendor\yiisoft\yii2\validators\UniqueValidator.php(135): yii\validators\UniqueValidator->modelExists('validateAttribute(Object(backend\models\search\TagSearch), 'makeUnique('trigger('runWithParams('[]')
#18 E:\root\yiicore.dg\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('handleRequest(Object(yii\web\Request))
#21 E:\root\yiicore.dg\backend\web\index.php(32): yii\base\Application->run()
#22 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column '0.slug' in 'where clause'
)
```

**Comment by loveorigami** [comment]
it is problem in last commot yii2. Now it fix it;
Try update

**Comment by loveorigami** [comment]
https://github.com/yiisoft/yii2/issues/14150

**Comment by Rapp-colince** [comment]
It works. Thanks.

**Comment by Beaten-Sect0r** [comment]
**loveorigami**, спасибо!
